version: '2'
services:
  server:
    build:
      context: ./server
    container_name: ucd-server
    image: ucd-server:6.2.1
    ports:
     - "8080:8080"
     - "8443:8443"
    networks: 
      - urbancode
    volumes:
      - codestation:/opt/ibm-ucd/server/var/repository
      - data:/opt/ibm-ucd/server/appdata/var/db
  agent:
    build:
      context: ./agent
    image: ucd-agent:6.2.1
    networks: 
      - urbancode 
networks:
  urbancode:
    driver: bridge
volumes: 
  codestation:
  data:
